services:
  comfyui:
    image: comfyui_cu128_v0812_fixed2_20260512:latest
    container_name: comfyui_cu128_v0812
    command:
      - python
      - main.py
      - --listen
      - 0.0.0.0
    ports:
      - "8189:8188"
    gpus:
      - count: all
        capabilities: ["gpu"]
    shm_size: "16g"
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - HF_HOME=/app/cache/huggingface
      - TRANSFORMERS_CACHE=/app/cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/app/cache/huggingface
      - TZ=Asia/Shanghai
    volumes:
      - "E:/AI_models:/app/models"
      - "E:/AI_Projects/ComfyUI-Project/input:/app/input"
      - "E:/AI_Projects/ComfyUI-Project/output:/app/output"
      - "E:/AI_Projects/ComfyUI-Project/cache:/app/cache"
    restart: "no"
